openapi: 3.0.1
info:
  title: Bear Notes Plugin API
  description: API for querying local Bear notes
  version: "1.0.0"

servers:
  - url: https://c29ba4fb2eaf.ngrok-free.app

paths:
  /search_notes:
    post:
      summary: 语义检索笔记
      operationId: searchNotes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                args:
                  type: object
                  properties:
                    query:
                      type: string
                      description: 查询关键词
      responses:
        "200":
          description: 成功返回匹配笔记
          content:
            application/json:
              schema:
                type: object
                properties:
                  notes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        content:
                          type: string

  /retrieve_for_rag:
    post:
      summary: 检索上下文（RAG 模式）
      operationId: retrieveForRag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                args:
                  type: object
                  properties:
                    query:
                      type: string
                      description: 查询文本
      responses:
        "200":
          description: 返回相似笔记上下文
          content:
            application/json:
              schema:
                type: object
                properties:
                  context:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        content:
                          type: string
                        score:
                          type: number

  /daily_insight_context:
    post:
      summary: 每日洞察生成与语义延展
      operationId: dailyInsightContext
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                args:
                  type: object
                  properties:
                    date:
                      type: string
                      description: 指定日期（可选）
      responses:
        "200":
          description: 返回每日洞察分析
          content:
            application/json:
              schema:
                type: object
                properties:
                  system_prompt:
                    type: string
                  today:
                    type: array
                    items:
                      type: object
                  related:
                    type: array
                    items:
                      type: object
