openapi: 3.0.1
info:
  title: Bear Notes Plugin API
  description: API for querying local Bear notes.
  version: "1.0.0"
servers:
  - url: https://30bf06ba4484.ngrok-free.app
paths:
  /query:
    post:
      operationId: query
      summary: 执行笔记搜索或读取操作
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:         # Added required field to prevent tool=undefined errors
                - tool
                - args
              properties:
                tool:
                  type: string
                  enum: [search_notes, get_tags, get_note, retrieve_for_rag]
                  description: 调用的工具名称
                args:
                  type: object
                  description: 工具所需的参数
      responses:
        "200":
          description: 成功响应
          content:
            application/json:
              schema:
                type: object
                properties:
                  notes:
                    type: array
                    items:
                      type: object
                  searchMethod:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
                  note:
                    type: object